### ISSUE TITLE
'Ignoring exception in on_message' thrown after first message

### ISSUE THREAD

**Issue by Dracon23** [Dwarf-Community/Dwarf#2]
Running into following exception after setting up everything:

```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/ryan/.venvs/dwarf/lib/python3.6/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "/opt/nfs/Projekte/runnershaven/dwarf/bot.py", line 175, in on_message
    member = core.get_member(message.author)
  File "/opt/nfs/Projekte/runnershaven/dwarf/core/api.py", line 310, in get_member
    return Member.objects.get(user=user_id, guild=guild_id)
  File "/home/ryan/.venvs/dwarf/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ryan/.venvs/dwarf/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
dwarf.models.DoesNotExist: Member matching query does not exist.
```

System details:

OS: Manjaro Linux
Python: 3.6.3
postgres version: 10.1
pip freeze:
```aiohttp==1.0.5
async-timeout==2.0.0
chardet==3.0.4
discord.py==0.16.12
Django==1.11.7
django-redis-cache==1.7.1
multidict==3.3.2
psycopg2==2.7.3.2
pycrypto==2.6.1
python-redis-lock==3.2.0
pytz==2017.3
redis==2.10.6
redis-cache==0.1.3
redis-structures==0.1.6
vital-tools==0.1.8
websockets==3.4
```

**Comment by AileenLumina** [comment]
Thanks for your help, a temporary fix was implemented in [5b4d775](https://github.com/Dwarf-Community/Dwarf/commit/5b4d7757673503b63199c5258a2d2f99ae3cdf9e), use `git pull` to update. :)

**Comment by Dracon23** [comment]
Pulled, works for now.

Are you hosting some docs to get started with extension development somewhere?

**Comment by AileenLumina** [comment]
Unfortunately, we haven't gotten to create a documentation for Dwarf. It is on our Trello board, though; we will build the docs using Sphinx, and they will be available via a Dwarf instance near you or the official website. :)
